modLoader = "javafml"
loaderVersion = "*"
license = "GPL"
issueTrackerURL = "https://github.com/henkelmax/sound-physics-remastered/issues"
[[mods]]
modId = "sound_physics_remastered"
version = "${mod_version}"
displayName = "Sound Physics Remastered"
updateJSONURL = "https://update.maxhenkel.de/neoforge/sound_physics_remastered"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/sound-physics-remastered"
logoFile = "icon.png"
authors = "Sonic Ether, vlad2305m, Max Henkel"
credits = "Sonic Ether, vlad2305m"
description = '''Provides realistic sound attenuation, reverberation, and absorption through blocks.'''
displayTest = "IGNORE_ALL_VERSION"
[[mixins]]
config = "sound_physics_remastered.mixins.json"
[[dependencies.sound_physics_remastered]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_dependency}"
ordering = "NONE"
side = "BOTH"
[[dependencies.sound_physics_remastered]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version}]"
ordering = "NONE"
side = "BOTH"
[[dependencies.sound_physics_remastered]]
modId = "cloth_config"
type = "optional"
versionRange = "[${cloth_config_version},)"
ordering = "AFTER"
side = "BOTH"
[[dependencies.sound_physics_remastered]]
modId = "voicechat"
type = "optional"
versionRange = "[${minecraft_version}-${voicechat_api_version},)"
ordering = "AFTER"
side = "BOTH"
